server {
    listen 80;

    location = /healthz {
        access_log off;
        return 200 'OK';
	default_type text/plain;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
